mfp:
  jwt:
    header: Authorization
    expiration: 86400
    secret: secret
  account:
    scheduled-updater-rate: 10000
    time-diff: 60
    percent-per-day: 1000.0
  stub:
    payment-service:
      enabled: true

  payment-service:
    main-bank-account-id: 11111111-2222-3333-4444-555555555555
    url: http://localhost:${server.port}
    api:
      create-account: /stub/accounts
      create-payment: /stub/payments
      find-currency-exchange-rates: /stub/currencyExchangeRates

  kafka:
    account:
      consumer-group: ACCOUNT
    user:
      topic: USER
    payment:
      topic: PAYMENT
    email:
      consumer-group: EMAIL

server:
  port: 8080
spring:
  application.name: mfp-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/mfp
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: thread
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5433/mfp
    user: postgres
    password: postgres
    change-log: db/changeLog/db.changelog-master.xml
    drop-first: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: flightsapplicationemailsender@gmail.com
    password: ${FLIGHTS_EMAIL_APPLICATION_PASSWORD}
    from: Flights Application
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: MFP_GROUP_ID
      auto-offset-reset: latest
