jwt:
  header: Authorization
  expiration: 86400
  secret: secret
spring:
  application.name: mfp-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mfp
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: thread
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/mfp
    user: postgres
    password: postgres
    change-log: db/changeLog/db.changelog-master.xml
    drop-first: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: flightsapplicationemailsender@gmail.com
    password: ${FLIGHTS_EMAIL_APPLICATION_PASSWORD}
    from: Flights Application
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
